server:
  port: 8080

jwt:
  secret: "fewafvedfjweklr"

mysql:
  host: localhost
  port: 3306
  dsn: root:admin@tcp(localhost:3306)/travel_assistant?charset=utf8mb4&parseTime=True&loc=Local&allowPublicKeyRetrieval=true&useSSL=false

baiduMap:
  key: "9EbmPr87yf1THBdLbvd5V1519JXhHOvS"
  basePath: "https://api.map.baidu.com"