version: '3'

tasks:
  swag:
    cmds:
      - swag init -g main.go -o ./docs

  build:
    deps: [swag]
    cmds:
      - go build -o bin/app.exe main.go

  run:
    deps: [swag]
    cmds:
      - go run main.go

  clean:
    cmds:
      - cmd: 'Remove-Item -Recurse -Force bin,docs'
        platforms: [windows]
      - cmd: 'rm -rf bin docs'
        platforms: [linux, darwin]