/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DayPlanItemCard: typeof import('./components/dayPlanItem/DayPlanItemCard.vue')['default']
    DayPlanItemForm: typeof import('./components/dayPlanItem/DayPlanItemForm.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TripCard: typeof import('./components/trip/TripCard.vue')['default']
    TripForm: typeof import('./components/trip/TripForm.vue')['default']
  }
}
