// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/activity/create": {
            "post": {
                "description": "为指定行程创建活动",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "创建活动",
                "parameters": [
                    {
                        "description": "创建活动请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateActivityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建活动成功",
                        "schema": {
                            "$ref": "#/definitions/entity.ActivityEntity"
                        }
                    }
                }
            }
        },
        "/api/v1/activity/delete": {
            "delete": {
                "description": "删除指定活动",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "删除活动",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "活动ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除活动成功"
                    }
                }
            }
        },
        "/api/v1/activity/list": {
            "get": {
                "description": "获取指定行程的活动列表，可按日期筛选",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "获取活动列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "行程ID",
                        "name": "tripId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日期筛选(yyyy-MM-dd)",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取活动列表成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.ActivityEntity"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/activity/route/query": {
            "post": {
                "description": "查询活动路线",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "查询活动路线",
                "parameters": [
                    {
                        "description": "查询活动路线请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CalcActivityRouteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询活动路线成功",
                        "schema": {
                            "$ref": "#/definitions/common.RouteResult"
                        }
                    }
                }
            }
        },
        "/api/v1/activity/update": {
            "put": {
                "description": "更新活动信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "更新活动",
                "parameters": [
                    {
                        "description": "更新活动请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateActivityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新活动成功",
                        "schema": {
                            "$ref": "#/definitions/entity.ActivityEntity"
                        }
                    }
                }
            }
        },
        "/api/v1/trip/create": {
            "post": {
                "description": "创建行程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trip"
                ],
                "summary": "创建行程",
                "parameters": [
                    {
                        "description": "创建行程请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateTripRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建行程成功",
                        "schema": {
                            "$ref": "#/definitions/entity.TripEntity"
                        }
                    }
                }
            }
        },
        "/api/v1/trip/delete": {
            "delete": {
                "description": "删除行程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trip"
                ],
                "summary": "删除行程",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "行程ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除行程成功",
                        "schema": {
                            "$ref": "#/definitions/entity.TripEntity"
                        }
                    }
                }
            }
        },
        "/api/v1/trip/get": {
            "get": {
                "description": "获取行程分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trip"
                ],
                "summary": "获取行程分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页条数",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取行程分页成功",
                        "schema": {
                            "$ref": "#/definitions/service.GetTripByPaginationResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/trip/update": {
            "put": {
                "description": "更新行程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trip"
                ],
                "summary": "更新行程",
                "parameters": [
                    {
                        "description": "更新行程请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateTripRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新行程成功",
                        "schema": {
                            "$ref": "#/definitions/entity.TripEntity"
                        }
                    }
                }
            }
        },
        "/api/v1/user/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/entity.UserEntity"
                        }
                    }
                }
            }
        },
        "/api/v1/user/register": {
            "post": {
                "description": "注册用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "注册用户",
                "parameters": [
                    {
                        "description": "注册请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/user.RegisterResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user/update": {
            "put": {
                "description": "更新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "更新用户",
                "parameters": [
                    {
                        "description": "更新用户请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新用户成功",
                        "schema": {
                            "$ref": "#/definitions/entity.UserEntity"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.Result": {
            "type": "object",
            "properties": {
                "routes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.Route"
                    }
                }
            }
        },
        "common.Route": {
            "type": "object",
            "properties": {
                "distance": {
                    "description": "路线距离，单位：米",
                    "type": "integer"
                },
                "duration": {
                    "description": "路线耗时，单位：秒",
                    "type": "integer"
                }
            }
        },
        "common.RouteResult": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/common.Result"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "entity.ActivityEntity": {
            "type": "object",
            "properties": {
                "activityDate": {
                    "description": "活动日期(yyyy-MM-dd)",
                    "type": "string"
                },
                "cost": {
                    "description": "总费用",
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "description": "活动描述",
                    "type": "string"
                },
                "endTime": {
                    "description": "结束时间(HH:mm)",
                    "type": "string"
                },
                "hotel": {
                    "description": "酒店",
                    "type": "string"
                },
                "hotelAddress": {
                    "description": "酒店地址",
                    "type": "string"
                },
                "hotelCost": {
                    "description": "酒店费用",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "location": {
                    "description": "活动地点",
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "startTime": {
                    "description": "开始时间(HH:mm)",
                    "type": "string"
                },
                "title": {
                    "description": "活动标题",
                    "type": "string"
                },
                "transportCost": {
                    "description": "交通费用",
                    "type": "integer"
                },
                "transportType": {
                    "description": "交通方式",
                    "type": "string"
                },
                "tripId": {
                    "description": "关联的行程ID",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entity.TripEntity": {
            "type": "object",
            "properties": {
                "activities": {
                    "description": "关联关系 - 行程有多个活动",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ActivityEntity"
                    }
                },
                "budget": {
                    "description": "预算",
                    "type": "number"
                },
                "cost": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "startDate": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userCount": {
                    "type": "integer"
                }
            }
        },
        "entity.UserEntity": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "car": {
                    "type": "string"
                },
                "carNumber": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "home": {
                    "type": "string"
                },
                "homeAddress": {
                    "type": "string"
                },
                "homeLatitude": {
                    "type": "number"
                },
                "homeLongitude": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "perKilometerCost": {
                    "description": "每公里油费",
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "service.CalcActivityRouteRequest": {
            "type": "object",
            "required": [
                "endActivityId",
                "startActivityId"
            ],
            "properties": {
                "endActivityId": {
                    "type": "integer"
                },
                "startActivityId": {
                    "type": "integer"
                }
            }
        },
        "service.CreateActivityRequest": {
            "type": "object",
            "required": [
                "activityDate",
                "cost",
                "endTime",
                "latitude",
                "longitude",
                "startTime",
                "title",
                "tripId"
            ],
            "properties": {
                "activityDate": {
                    "type": "string"
                },
                "cost": {
                    "type": "integer",
                    "minimum": 0
                },
                "description": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "hotel": {
                    "type": "string",
                    "maxLength": 255
                },
                "hotelAddress": {
                    "type": "string",
                    "maxLength": 255
                },
                "hotelCost": {
                    "type": "integer",
                    "minimum": 0
                },
                "latitude": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "startTime": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 255
                },
                "transportCost": {
                    "type": "integer",
                    "minimum": 0
                },
                "transportType": {
                    "type": "string",
                    "maxLength": 255
                },
                "tripId": {
                    "type": "integer"
                }
            }
        },
        "service.CreateTripRequest": {
            "type": "object",
            "required": [
                "budget",
                "endDate",
                "startDate",
                "title",
                "userCount"
            ],
            "properties": {
                "budget": {
                    "type": "number",
                    "minimum": 0
                },
                "description": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 0
                },
                "endDate": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "userCount": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "service.GetTripByPaginationResponse": {
            "type": "object",
            "properties": {
                "trips": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.TripEntity"
                    }
                }
            }
        },
        "service.UpdateActivityRequest": {
            "type": "object",
            "required": [
                "activityDate",
                "cost",
                "endTime",
                "id",
                "latitude",
                "longitude",
                "startTime",
                "title",
                "tripId"
            ],
            "properties": {
                "activityDate": {
                    "type": "string"
                },
                "cost": {
                    "type": "integer",
                    "minimum": 0
                },
                "description": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "hotel": {
                    "type": "string",
                    "maxLength": 255
                },
                "hotelAddress": {
                    "type": "string",
                    "maxLength": 255
                },
                "hotelCost": {
                    "type": "integer",
                    "minimum": 0
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "startTime": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 255
                },
                "transportCost": {
                    "type": "integer",
                    "minimum": 0
                },
                "transportType": {
                    "type": "string",
                    "maxLength": 255
                },
                "tripId": {
                    "type": "integer"
                }
            }
        },
        "service.UpdateTripRequest": {
            "type": "object",
            "required": [
                "budget",
                "endDate",
                "id",
                "startDate",
                "title",
                "userCount"
            ],
            "properties": {
                "budget": {
                    "type": "number",
                    "minimum": 0
                },
                "description": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 0
                },
                "endDate": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "startDate": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "userCount": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "user.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "必填，6-20位",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                },
                "username": {
                    "description": "必填，3-20位字母数字",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                }
            }
        },
        "user.RegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "必填，6-20位",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                },
                "phone": {
                    "description": "可选，11位数字",
                    "type": "string"
                },
                "username": {
                    "description": "必填，3-20位字母数字",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                }
            }
        },
        "user.RegisterResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "user.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "car": {
                    "type": "string",
                    "maxLength": 255
                },
                "carNumber": {
                    "type": "string",
                    "maxLength": 255
                },
                "home": {
                    "type": "string",
                    "maxLength": 255
                },
                "homeAddress": {
                    "type": "string",
                    "maxLength": 255
                },
                "homeLatitude": {
                    "type": "number"
                },
                "homeLongitude": {
                    "type": "number"
                },
                "perKilometerCost": {
                    "type": "integer",
                    "minimum": 0
                },
                "phone": {
                    "description": "可选，11位数字",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Travel Assistant API",
	Description:      "旅游助手 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
